name: hello-world

on:
  push:
    paths:
      - 'basics/tasks/hello-world/**'
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Set up CMake
        uses: martinlindhe/cmake-action@v2
        
      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y cmake libgtest-dev
        
      - name: Configure and build
        run: |
          cmake -S . -B build
          cmake --build build
          
      - name: Run tests
        run: |
          cd build
          ./hello_test

