name: Plagiarism Check

on:
  pull_request:
    branches:
      - main

jobs:
  check-plagiarism:
    runs-on: ubuntu-latest
    permissions:
      issues: write

    steps:
    - name: Checkout the base repository
      uses: actions/checkout@v2

    - name: Checkout the plagiarism check tool
      uses: actions/checkout@v2
      with:
        repository: 'Gamezar/openai-plagiat-score'
        path: 'openai-plagiat-score'
        ref: 'main'

    - name: Install plagiarism check tool dependencies
      run: |
        cd openai-plagiat-score
        chmod +x install.sh
        ./install.sh

    - name: List all changed files
      id: files
      run: |
        echo "files=$(git diff --name-only ${{ github.event.before }} ${{ github.event.after }})" >> $GITHUB_ENV

    - name: Run plagiarism check on all changed files
      id: plagiarism_check
      run: |
        cd openai-plagiat-score
        output=""
        for file in ${{ env.files }}
        do
          result=$(python main.py "$file")
          output+="$file: $result\n"
        done
        echo "::set-output name=result::$output"

    - name: Post comment
      uses: KeisukeYamashita/create-comment@v1
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        comment: |
          Issue title must start with 'ABC-'.
          Auto-closing this issue.

    - name: Finalize check
      run: echo "Plagiarism check completed successfully."
